### ISSUE TITLE
请问能发布一个Windows下的binary release吗？

### ISSUE THREAD

**Issue by pymo** [arucil/gvbasic-simulator4cpp#1]
尝试了一下在Windows下面编译，但是模拟的文曲星屏幕没有显示，也不知道怎么debug。请问开发者能发布一个Windows binary方便普通人使用吗？谢谢！

**Comment by arucil** [comment]
windows版本已经编译发布，在release页面 <https://github.com/arucil/gvbasic-simulator4cpp/releases/tag/1.0.0>

**Comment by pymo** [comment]
多谢！
