### ISSUE TITLE
linux怎么安装？新人

### ISSUE THREAD

**Issue by hqy662** [arucil/gvbasic-simulator4cpp#2]
哪里下载包？

**Comment by arucil** [comment]
linux要自己编译，我建议你还是用 [wqxtools](https://github.com/arucil/wqxtools)，自带gvb编辑器，可以直接打开.bas文件，不需要转换成.txt，我编译了 linux程序，在 [这里](https://gitlab.com/arucil/wqxtools-release/-/releases/0.2.0) 下载
